plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Francois\\OneDrive\\curious-traveller\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/sw.js"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/registerSW.js"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"